# SPDX-License-Identifier: GPL-2.0

# required for overlay support
DTC_FLAGS += -@

# DTB Overlays for Maaxboard
dtbo-y += maaxboard-mipi.dtbo
dtbo-y += maaxboard-as0260.dtbo
dtbo-y += maaxboard-dual-display.dtbo
dtbo-y += maaxboard-ext-gpio.dtbo
dtbo-y += maaxboard-ext-i2c.dtbo
dtbo-y += maaxboard-ext-pwm.dtbo
dtbo-y += maaxboard-ext-sai2.dtbo
dtbo-y += maaxboard-ext-spi.dtbo
dtbo-y += maaxboard-ext-uart2.dtbo
dtbo-y += maaxboard-ext-wm8960.dtbo
dtbo-y += maaxboard-hdmi.dtbo
dtbo-y += maaxboard-ov5640.dtbo
dtbo-y += maaxboard-usb0-device.dtbo

# # DTB Overlays for Maaxboard-Nano
dtbo-y += maaxboard-nano-mipi.dtbo
dtbo-y += maaxboard-nano-mipi-oldpanel.dtbo
dtbo-y += maaxboard-nano-audio.dtbo
dtbo-y += maaxboard-nano-mic.dtbo
dtbo-y += maaxboard-nano-ov5640.dtbo
dtbo-y += maaxboard-nano-ext-gpio.dtbo
dtbo-y += maaxboard-nano-ext-i2c.dtbo
dtbo-y += maaxboard-nano-ext-pwm.dtbo
dtbo-y += maaxboard-nano-ext-spi.dtbo
dtbo-y += maaxboard-nano-ext-uart4.dtbo
dtbo-y += maaxboard-nano-ext-sai3.dtbo
