# SPDX-License-Identifier: GPL-2.0

# required for overlay support
DTC_FLAGS += -@

dtbo-y += maaxboard-hdmi.dtbo
dtbo-y += maaxboard-mipi.dtbo
dtbo-y += maaxboard-dual-display.dtbo
dtbo-y += maaxboard-ext-gpio.dtbo
dtbo-y += maaxboard-ext-i2c.dtbo
dtbo-y += maaxboard-ext-pwm.dtbo
dtbo-y += maaxboard-ext-sai2.dtbo
dtbo-y += maaxboard-ext-spi.dtbo
dtbo-y += maaxboard-ext-uart2.dtbo
dtbo-y += maaxboard-ext-wm8960.dtbo
dtbo-y += maaxboard-ov5640.dtbo
dtbo-y += maaxboard-as0260.dtbo
dtbo-y += maaxboard-usb0-device.dtbo

